### ISSUE TITLE
Any way to use India as a region?

### ISSUE THREAD

**Issue by yashendra2797** [AyumuKasuga/steambot#1]
I know its not an issue, just wanted to know if it was possible. Thanks!

**Comment by AyumuKasuga** [comment]
Hello! I just added India region :)

![image](https://cloud.githubusercontent.com/assets/700142/22220507/0fa0c406-e1c0-11e6-877b-f5b5e3a31f7a.png)

And looks like it works

![image](https://cloud.githubusercontent.com/assets/700142/22220551/2e2e3b2e-e1c0-11e6-8c4b-836ea66d9fb9.png)

**Comment by yashendra2797** [comment]
Perfect. Thank you so much!
