### ISSUE TITLE
Using inline search makes the bot respond with 'Nothing found' after giving the result.

### ISSUE THREAD

**Issue by yashendra2797** [AyumuKasuga/steambot#2]
Hey, sorry for two issues in as many days. I was really (pleasantly) surprised that you added support for IN region in just a few hours of my query.

So, I'm facing a bug. When I use the Inline search `@StoreSteamBot [GAME NAME]` and use the bot, it will give me some results, clicking one of which will output the name, Price, and Link to the chat. All in all, perfect. But then because it was tagged in the search, it will respond with a 'Nothing found'.

I don't know if this is a bug, or if I'm doing something wrong.

Please let me know if I can do anything to help you out. I use the same username (@yashendra2797) everywhere, so contact me on Telegram if needed.

Here's a screenshot of the bug.

![screenshot 2017-01-24 04 54 13](https://cloud.githubusercontent.com/assets/8304724/22228098/d77a2862-e1f4-11e6-82cd-a7bff596a4cb.png)

Thanks!

**Comment by AyumuKasuga** [comment]
Hello! Thank you for your report. But it's not a bug. Inline search in telegram bots is for using it in chat with another person or group chat, not for chatting with bot. So when you send bot inline search result it trying to find game by this string, which includes price and url, and steam answers with empty result. Of course i can handle this situation but i don't think it's necessary :)

Also you can read more about inline bots [here](https://core.telegram.org/bots/inline)

**Comment by yashendra2797** [comment]
Thanks for the clarification. Sorry for bothering you 😊

EDIT: Found the 'Error'. My friend/other admin had added the bot the group as a member. He told me when I mentioned this 'issue' to him. Kicked the bot from the group, and inline search works perfect. Nothing more than a simple [ID10T error](http://www.webopedia.com/TERM/I/id10t_error.html).

Thanks!
